import type { TripListItem } from './types';

/** 여행 목록 API가 연결되기 전 화면 확인에만 사용하는 임시 데이터입니다. */
export const previewTrips: TripListItem[] = [
  {
    id: 1,
    name: '파리 & 런던',
    locations: ['파리', '런던'],
    startDate: '2025-11-20',
    endDate: '2025-11-27',
    nights: 7,
    photoCount: 341,
    favorite: true,
    processingStatus: 'ready',
  },
  {
    id: 2,
    name: '이천 가을 여행',
    locations: ['이천'],
    startDate: '2025-10-03',
    endDate: '2025-10-05',
    nights: 2,
    photoCount: 18,
    favorite: true,
    processingStatus: 'ready',
  },
  {
    id: 3,
    name: '여주 봄 나들이',
    locations: ['여주', '양평'],
    startDate: '2026-04-11',
    endDate: '2026-04-12',
    nights: 1,
    photoCount: 0,
    favorite: false,
    processingStatus: 'processing',
  },
  {
    id: 4,
    name: '제주 한 바퀴',
    locations: ['제주시', '서귀포', '우도'],
    startDate: '2026-02-14',
    endDate: '2026-02-18',
    nights: 4,
    photoCount: 126,
    favorite: false,
    processingStatus: 'ready',
  },
  {
    id: 5,
    name: '서울 주말 산책',
    locations: ['서울'],
    startDate: '2026-01-10',
    endDate: '2026-01-11',
    nights: 1,
    photoCount: 43,
    favorite: false,
    processingStatus: 'ready',
  },
];
